version: '3'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/timescaledb
    healthcheck:
      test: "pg_isready --username=metrics-server && psql --username=metrics-server --list"
      timeout: 10s
      retries: 20
    networks:
      - app-tier

  metrics-server-api:
    build:
      context: ./
      dockerfile: Dockerfile.server
    container_name: metrics-server-api
    depends_on:
      - timescaledb
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=timescaledb
      - WAIT_HOSTS=timescaledb:5432
    networks:
      - app-tier

  simulator:
    build:
      context: ./
      dockerfile: Dockerfile.simulator
    container_name: metrics-server-simulator
    depends_on:
      - metrics-server-api
    env_file:
      - .env
    environment:
      - METRICS_SERVER_URL=http://metrics-server-api:8080
      - WAIT_HOSTS=metrics-server-api:8080
    profiles: [ "simulator" ]
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
