FROM golang:1.21.6-alpine3.19 AS builder

RUN apk update && apk add --no-cache gcc musl-dev make

WORKDIR /app

COPY . .

RUN make dependency
RUN make server

FROM alpine:3.19

WORKDIR /app
COPY --from=builder /app/bin/metrics-server-api /app

EXPOSE 8080

# Add docker-compose-wait tool
ENV WAIT_VERSION 2.9.0
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

CMD /wait && ./metrics-server-api
