version: '3'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/timescaledb
    networks:
      - app-tier

  metrics-server-api:
    build:
      context: ./
      dockerfile: Dockerfile.server
    container_name: metrics-server-api
    depends_on:
      - timescaledb
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=timescaledb
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
